databases:
  - name: chalary-db
    databaseName: chalary_db
    user: chalary_user
    plan: free

services:
  - type: redis
    name: chalary-redis
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: []

  - type: web
    name: chalary-web
    env: python
    region: oregon
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true   # ✅ only here
      - key: DATABASE_URL
        fromDatabase:
          name: chalary-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: chalary-redis
          property: connectionString
      - key: DEBUG
        value: "false"

  - type: worker
    name: chalary-worker
    env: python
    region: oregon
    plan: free
    buildCommand: ./build.sh
    startCommand: celery -A core worker -l info --concurrency=4
    envVars:
      - key: SECRET_KEY
        fromService:
          type: web
          name: chalary-web
          property: envVars.SECRET_KEY   # ✅ inherit from web
      - key: DATABASE_URL
        fromDatabase:
          name: chalary-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: chalary-redis
          property: connectionString
      - key: DEBUG
        value: "false"

  - type: worker
    name: chalary-beat
    env: python
    region: oregon
    plan: free
    buildCommand: ./build.sh
    startCommand: celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    envVars:
      - key: SECRET_KEY
        fromService:
          type: web
          name: chalary-web
          property: envVars.SECRET_KEY   # ✅ inherit from web
      - key: DATABASE_URL
        fromDatabase:
          name: chalary-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: chalary-redis
          property: connectionString
      - key: DEBUG
        value: "false"
