services:
  - type: web
    name: django-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DATABASE_URL
        fromService:
          name: postgres
          type: postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: redis
          type: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

  - type: worker
    name: celery-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A core worker --loglevel=info
    envVars:
      - key: DATABASE_URL
        fromService:
          name: postgres
          type: postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: redis
          type: redis
          property: connectionString
      - key: SECRET_KEY
        fromService:
          name: django-app
          property: env.SECRET_KEY

  - type: redis
    name: redis
    plan: free
    ipAllowList: [] # Allow all IPs

  - type: postgres
    name: postgres
    plan: free