databases:
  - name: course-platform-db
    plan: free

services:
  # Django Web Service
  - type: web
    name: course-platform-web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: daphne -b 0.0.0.0 -p $PORT core.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: course-platform-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: course-platform-redis
          type: redis
          property: connectionString

  # Celery Worker
  - type: worker
    name: course-platform-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A core worker -l info
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: DATABASE_URL
        fromDatabase:
          name: course-platform-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: course-platform-redis
          type: redis
          property: connectionString

  # Celery Beat
  - type: worker
    name: course-platform-beat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A core beat -l info
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: DATABASE_URL
        fromDatabase:
          name: course-platform-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: course-platform-redis
          type: redis
          property: connectionString

  # Redis for Channels + Celery
  - type: redis
    name: course-platform-redis
    plan: free
