from django.urls import path
from .views import (
    RegisterView,
    LoginView,
    RequestOTPView,
    VerifyOTPView,
    VerifyEmailView,
    ChangePasswordView,
    RequestPasswordResetView,
    ResetPasswordView,
    resend_verification_email,
    LogoutView,
    UserProfileView,
    UserProfileUpdateView,
    UserProfileDeleteView

)

urlpatterns = [
    path(
        'register/',
        RegisterView.as_view(),
        name='register'
    ),
    path(
        'login/',
        LoginView.as_view(),
        name='login'
    ),
    path(
        'request-otp/',
        RequestOTPView.as_view(),
        name='request_otp'
    ),
    path(
        'verify-otp/',
        VerifyOTPView.as_view(),
        name='verify_otp'
    ),
    path(
        'verify-email/<uuid:token>/',
        VerifyEmailView.as_view(),
        name='verify_email'
    ),
    path(
        'resend-verification/',
        resend_verification_email,
        name='resend_verification'
    ),
    path(
        'change-password/',
        ChangePasswordView.as_view(),
        name='change_password'
    ),
    path(
        'request-password-reset/',
        RequestPasswordResetView.as_view(),
        name='request_password-reset'
    ),
    path(
        'confirm-reset-password/',
        ResetPasswordView.as_view(),
        name='confirm_reset_password'
    ),
    path(
        'profile/',
        UserProfileView.as_view(),
        name='profile'
    ),
    path(
        'profile/update/',
        UserProfileUpdateView.as_view(),
        name='profile_update'
    ),
    path(
        'profile/delete/',
        UserProfileDeleteView.as_view(),
        name='profile_delete'
    ),
    path(
        'logout/',
        LogoutView.as_view(),
        name='logout'
    ),
]
