from django.urls import path
from .views.catagory import (
    CategoryListView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    CatagoryDetailView
)
from .views.courses import (
    CourseListView,
    CourseCreateView,
    CourseDetailView,
    CourseUpdateView,
    CourseDeleteView,
    course_analytics
)
from .views.enrollment import (
    EnrollmentCreateView,
    EnrollmentListView
)
from .views import ModuleListView
from .views.lesson import LessonDetailView
from .views.progress import (
    ProgressUpdateView,
    student_progress_report
)

urlpatterns = [
    path(
        'categories/',
        CategoryListView.as_view(),
        name='category_list'
    ),
    path(
        'category-detail/<int:pk>/',
        CatagoryDetailView.as_view(),
        name='category_detail'
    ),
    path(
        'categories/create/',
        CategoryCreateView.as_view(),
        name='category_create'
    ),
    path(
        'categories/<int:pk>/update/',
        CategoryUpdateView.as_view(),
        name='category_update'
    ),
    
    path(
        'categories/<int:pk>/delete/',
        CategoryDeleteView.as_view(),
        name='category_delete'
    ),
    path(
        '',
        CourseListView.as_view(),
        name='course_list'
    ),
    path(
        'create/',
        CourseCreateView.as_view(),
        name='course_create'
    ),
    path(
        '<int:pk>/detail/',
        CourseDetailView.as_view(),
        name='course_detail'
    ),
    path(
        '<int:pk>/update/',
        CourseUpdateView.as_view(),
        name='course_update'
    ),
    path(
        '<int:pk>/delete/',
        CourseDeleteView.as_view(),
        name='course_delete'
    ),
    path(
        '<int:course_id>/analytics/',
        course_analytics,
        name='course_analytics'
    ),
    path(
        '<int:course_id>/enroll/',
        EnrollmentCreateView.as_view(),
        name='enroll'
    ),
    path(
        'enrollments/',
        EnrollmentListView.as_view(),
        name='enrollment_list'
    ),
    path(
        '<int:course_id>/modules/',
        ModuleListView.as_view(),
        name='module_list'
    ),
    path(
        'lessons/<int:pk>/',
        LessonDetailView.as_view(),
        name='lesson_detail'
    ),
    path(
        'progress/<int:pk>/',
        ProgressUpdateView.as_view(),
        name='progress_update'
    ),
    path(
        '<int:course_id>/progress-report/',
        student_progress_report,
        name='progress_report'
    ),
]
