from django.urls import path
from .views.catagory import (
    CategoryListView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView
)
from .views.courses import (
    CourseListView,
    CourseCreateView,
    CourseDetailView,
    CourseUpdateView,
    CourseDeleteView,
    course_analytics
)
from .views.enrollment import (
    EnrollmentCreateView,
    EnrollmentListView
)
from .views import ModuleListView
from .views.lesson import LessonDetailView
from .views.progress import (
    ProgressUpdateView,
    student_progress_report
)

urlpatterns = [
    path(
        'categories/',
        CategoryListView.as_view(),
        name='category-list'
    ),
    path(
        'categories/create/',
        CategoryCreateView.as_view(),
        name='category-create'
    ),
    path(
        'categories/<int:pk>/update/',
        CategoryUpdateView.as_view(),
        name='category-update'
    ),
    
    path(
        'categories/<int:pk>/delete/',
        CategoryDeleteView.as_view(),
        name='category-delete'
    ),
    path(
        '',
        CourseListView.as_view(),
        name='course-list'
    ),
    path(
        'create/',
        CourseCreateView.as_view(),
        name='course-create'
    ),
    path(
        '<int:pk>/detail/',
        CourseDetailView.as_view(),
        name='course-detail'
    ),
    path(
        '<int:pk>/update/',
        CourseUpdateView.as_view(),
        name='course-update'
    ),
    path(
        '<int:pk>/delete/',
        CourseDeleteView.as_view(),
        name='course-delete'
    ),
    path(
        '<int:course_id>/analytics/',
        course_analytics,
        name='course-analytics'
    ),
    path(
        '<int:course_id>/enroll/',
        EnrollmentCreateView.as_view(),
        name='enroll'
    ),
    path(
        'enrollments/',
        EnrollmentListView.as_view(),
        name='enrollment-list'
    ),
    path(
        '<int:course_id>/modules/',
        ModuleListView.as_view(),
        name='module-list'
    ),
    path(
        'lessons/<int:pk>/',
        LessonDetailView.as_view(),
        name='lesson-detail'
    ),
    path(
        'progress/<int:pk>/',
        ProgressUpdateView.as_view(),
        name='progress-update'
    ),
    path(
        '<int:course_id>/progress-report/',
        student_progress_report,
        name='progress-report'
    ),
]
