from django.urls import path
from .views.catagory import (
    CategoryListView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    CatagoryDetailView
)
from .views.courses import (
    CourseListView,
    CourseCreateView,
    CourseDetailView,
    CourseUpdateView,
    CourseDeleteView,
    course_analytics
)
from .views.enrollment import (
    EnrollmentCreateView,
    EnrollmentListView
)
from .views import (
    ModuleListView,
    CourseModuleCreateView,
    ModuleUpdateView,
    ModuleDeleteView
)
from .views.lesson import (
    LessonDetailView,
    LessonCreateView,
    LessonUpdateView,
    LessonDeleteView
)
from .views.progress import (
    ProgressUpdateView,
    student_progress_report
)

from .views.progress_view import (
    ProgressListView,
    ProgressCreateView,
    ProgressDetailView,
    ProgressBulkUpdateView,
    progress_stats
)
urlpatterns = [
    path(
        'categories/',
        CategoryListView.as_view(),
        name='category_list'
    ),
    path(
        'category/detail/<int:pk>/',
        CatagoryDetailView.as_view(),
        name='category_detail'
    ),
    path(
        'category/create/',
        CategoryCreateView.as_view(),
        name='category_create'
    ),
    path(
        'category/<int:pk>/update/',
        CategoryUpdateView.as_view(),
        name='category_update'
    ),
    
    path(
        'category/<int:pk>/delete/',
        CategoryDeleteView.as_view(),
        name='category_delete'
    ),
    path(
        '',
        CourseListView.as_view(),
        name='course_list'
    ),
    path(
        'create/',
        CourseCreateView.as_view(),
        name='course_create'
    ),
    path(
        '<int:pk>/detail/',
        CourseDetailView.as_view(),
        name='course_detail'
    ),
    path(
        '<int:pk>/update/',
        CourseUpdateView.as_view(),
        name='course_update'
    ),
    path(
        '<int:pk>/delete/',
        CourseDeleteView.as_view(),
        name='course_delete'
    ),
    path(
        '<int:course_id>/analytics/',
        course_analytics,
        name='course_analytics'
    ),
    path(
        '<int:course_id>/enroll/',
        EnrollmentCreateView.as_view(),
        name='enroll'
    ),
    path(
        'enrollments/',
        EnrollmentListView.as_view(),
        name='enrollment_list'
    ),
    path(
        '<int:course_id>/modules/',
        ModuleListView.as_view(),
        name='module_list'
    ),
    path(
        '<int:course_id>/modules/create/',
        CourseModuleCreateView.as_view(),
        name='module_create'
    ),
    path(
        'modules/<int:pk>/update/',
        ModuleUpdateView.as_view(),
        name='module_update'
    ),
    path(
        'modules/<int:pk>/delete/',
        ModuleDeleteView.as_view(),
        name='module_delete'
    ),
    path(
        'lessons/<int:pk>/',
        LessonDetailView.as_view(),
        name='lesson_detail'
    ),
    path(
        '<int:module_id>/lessons/create/',
        LessonCreateView.as_view(),
        name='lesson_create'
    ),
    path(
        'lessons/<int:pk>/update/',
        LessonUpdateView.as_view(),
        name='lesson_update'
    ),
    path(
        'lessons/<int:pk>/delete/',
        LessonDeleteView.as_view(),
        name='lesson_delete'
    ),
    path(
        'progress/<int:pk>/',
        ProgressUpdateView.as_view(),
        name='progress_update'
    ),
    path(
        '<int:course_id>/progress-report/',
        student_progress_report,
        name='progress_report'
    ),
    path(
        'progress/',
        ProgressListView.as_view(),
        name='progress-list'
    ),
    path(
        'progress/create/',
        ProgressCreateView.as_view(),
        name='progress-create'
    ),
    path(
        'progress/bulk-update/',
        ProgressBulkUpdateView.as_view(),
        name='progress-bulk-update'
    ),
    path(
        'progress/<int:pk>/',
        ProgressDetailView.as_view(),
        name='progress-detail'
    ),
    path(
        'progress/stats/',
        progress_stats,
        name='progress-stats'
    ),

]
